<?php
/**
 * Installer for photo-proofing-WD
 * Designed by WowkDigital
 */

$configFile = __DIR__ . '/api/config.php';
$dbDir = __DIR__ . '/data';
$photosDir = __DIR__ . '/photos';
$logsDir = __DIR__ . '/selection_logs';

// Check if already installed
if (file_exists($configFile)) {
    $alreadyInstalled = true;
} else {
    $alreadyInstalled = false;
}

$errors = [];
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$alreadyInstalled) {
    $albumTitle = $_POST['album_title'] ?? 'My Photo Gallery';
    $password = $_POST['admin_password'] ?? '';
    
    // Contact Links
    $contactTelegram = $_POST['contact_telegram'] ?? '';
    $contactWhatsapp = $_POST['contact_whatsapp'] ?? '';
    $contactFacebook = $_POST['contact_facebook'] ?? '';
    $contactInstagram = $_POST['contact_instagram'] ?? '';
    $contactSignal = $_POST['contact_signal'] ?? '';

    // Telegram Bot
    $tgEnabled = isset($_POST['telegram_bot_enabled']) ? '1' : '0';
    $tgToken = $_POST['telegram_bot_token'] ?? '';
    $tgChatId = $_POST['telegram_chat_id'] ?? '';

    if (strlen($password) < 6) {
        $errors[] = "Password must be at least 6 characters long.";
    }

    if (empty($errors)) {
        // 1. Create Directories
        $dirsToCreate = [$dbDir, $photosDir, $photosDir . '/thumbnails', $logsDir, __DIR__ . '/api'];
        foreach ($dirsToCreate as $dir) {
            if (!file_exists($dir)) {
                @mkdir($dir, 0777, true);
            }
        }

        // 2. Generate config.php
        $configContent = "<?php\n";
        $configContent .= "/**\n * Configuration generated by Installer\n */\n\n";
        $configContent .= "require_once __DIR__ . '/db.php';\n\n";
        $configContent .= "// Load settings from database\n";
        $configContent .= "try {\n";
        $configContent .= "    \$stmt = \$pdo->query(\"SELECT key, value FROM settings\");\n";
        $configContent .= "    while (\$row = \$stmt->fetch()) {\n";
        $configContent .= "        \$val = \$row['value'];\n";
        $configContent .= "        // Convert '1'/'0' to true/false for boolean settings\n";
        $configContent .= "        if (in_array(\$row['key'], ['TELEGRAM_BOT_ENABLED', 'PASSWORD_PROTECTION_ENABLED'])) {\n";
        $configContent .= "            \$val = (\$val === '1' || \$val === 'true');\n";
        $configContent .= "        }\n";
        $configContent .= "        if (!defined(\$row['key'])) define(\$row['key'], \$val);\n";
        $configContent .= "    }\n";
        $configContent .= "} catch (Exception \$e) {\n";
        $configContent .= "    // Settings table might not exist yet during migration\n";
        $configContent .= "}\n";

        if (file_put_contents($configFile, $configContent)) {
            // 3. Initialize Database
            try {
                $dbPath = $dbDir . '/database.sqlite';
                $pdo = new PDO('sqlite:' . $dbPath);
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                // Settings Table
                $pdo->exec("CREATE TABLE IF NOT EXISTS settings (
                    key TEXT PRIMARY KEY,
                    value TEXT
                )");

                // Albums Table
                $pdo->exec("CREATE TABLE IF NOT EXISTS albums (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    slug TEXT NOT NULL UNIQUE,
                    internal_name TEXT,
                    public_title TEXT,
                    encryption_key_hash TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
                )");

                // Photos Table
                $pdo->exec("CREATE TABLE IF NOT EXISTS photos (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    filename TEXT NOT NULL UNIQUE,
                    original_filename TEXT,
                    upload_date DATETIME DEFAULT CURRENT_TIMESTAMP,
                    album_id INTEGER REFERENCES albums(id) ON DELETE SET NULL
                )");

                // Selections Table
                $pdo->exec("CREATE TABLE IF NOT EXISTS selections (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    client_name TEXT NOT NULL,
                    client_email TEXT,
                    client_phone TEXT,
                    client_instagram TEXT,
                    client_telegram TEXT,
                    client_facebook TEXT,
                    client_notes TEXT,
                    selection_date DATETIME DEFAULT CURRENT_TIMESTAMP,
                    ip_address TEXT,
                    album_id INTEGER REFERENCES albums(id) ON DELETE SET NULL
                )");

                // Selected Photos Table
                $pdo->exec("CREATE TABLE IF NOT EXISTS selected_photos (
                    selection_id INTEGER NOT NULL,
                    photo_filename TEXT NOT NULL,
                    FOREIGN KEY (selection_id) REFERENCES selections(id) ON DELETE CASCADE
                )");

                // Insert Settings
                $settings = [
                    'ALBUM_TITLE' => $albumTitle,
                    'ADMIN_PASSWORD_HASH' => password_hash($password, PASSWORD_DEFAULT),
                    'PASSWORD_PROTECTION_ENABLED' => '0',
                    'GALLERY_PASSWORD' => 'change-me',
                    'CONTACT_TELEGRAM' => $contactTelegram,
                    'CONTACT_FACEBOOK' => $contactFacebook,
                    'CONTACT_SIGNAL' => $contactSignal,
                    'CONTACT_WHATSAPP' => $contactWhatsapp,
                    'CONTACT_INSTAGRAM' => $contactInstagram,
                    'TELEGRAM_BOT_ENABLED' => $tgEnabled,
                    'TELEGRAM_BOT_TOKEN' => $tgToken,
                    'TELEGRAM_CHAT_ID' => $tgChatId
                ];

                $stmt = $pdo->prepare("INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)");
                foreach ($settings as $k => $v) {
                    $stmt->execute([$k, $v]);
                }

                // Add default album
                $count = $pdo->query("SELECT COUNT(*) FROM albums")->fetchColumn();
                if ($count == 0) {
                    $pdo->prepare("INSERT INTO albums (slug, internal_name, public_title) VALUES (?, ?, ?)")
                        ->execute(['default', 'Main Album', $albumTitle]);
                }

                $success = true;
            } catch (PDOException $e) {
                $errors[] = "Database error: " . $e->getMessage();
            }
        } else {
            $errors[] = "Could not write api/config.php. Check permissions.";
        }
    }
}

// Permission Checks
$permissions = [
    'data' => is_writable($dbDir) || @mkdir($dbDir, 0777, true),
    'photos' => is_writable($photosDir) || @mkdir($photosDir, 0777, true),
    'api' => is_writable(__DIR__ . '/api')
];

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install | photo-proofing-WD</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/lucide@latest"></script>
    <style>
        body { font-family: 'Outfit', sans-serif; background-color: #0f172a; }
        .glass { background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(12px); border: 1px solid rgba(255, 255, 255, 0.1); }
        .input-dark { background: rgba(15, 23, 42, 0.6); border: 1px solid rgba(255, 255, 255, 0.1); color: white; }
        .input-dark:focus { border-color: #6366f1; ring: 2px; ring-color: #6366f1; outline: none; }
    </style>
</head>
<body class="text-gray-200 min-h-screen flex items-center justify-center p-6">

    <div class="glass max-w-3xl w-full rounded-3xl shadow-2xl p-8 md:p-12">
        
        <div class="flex items-center gap-6 mb-10">
            <div class="bg-indigo-600 p-4 rounded-2xl shadow-lg shadow-indigo-500/20">
                <i data-lucide="shield-check" class="text-white w-8 h-8"></i>
            </div>
            <div>
                <h1 class="text-3xl font-bold text-white">Installation Wizard</h1>
                <p class="text-gray-400">Setup your photo-proofing environment</p>
            </div>
        </div>

        <?php if ($success): ?>
            <div class="bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 p-6 rounded-2xl mb-8 flex items-start gap-4">
                <i data-lucide="check-circle" class="w-6 h-6 shrink-0"></i>
                <div>
                    <h3 class="font-bold text-lg text-white">Installation Successful!</h3>
                    <p class="mt-1 text-emerald-400/80">Everything is ready. Please <strong>delete install.php</strong> for security.</p>
                    <a href="admin/" class="inline-flex items-center gap-2 mt-6 px-8 py-3 bg-indigo-600 text-white rounded-xl hover:bg-indigo-700 transition-all font-bold">
                        Enter Admin Panel <i data-lucide="arrow-right" class="w-4 h-4"></i>
                    </a>
                </div>
            </div>
        <?php elseif ($alreadyInstalled): ?>
            <div class="bg-amber-500/10 border border-amber-500/20 text-amber-400 p-6 rounded-2xl mb-8 flex items-start gap-4">
                <i data-lucide="alert-triangle" class="w-6 h-6 shrink-0"></i>
                <div>
                    <h3 class="font-bold text-white">System Already Configured</h3>
                    <p class="mt-1 text-amber-400/80">The `api/config.php` exists. To reinstall, delete this file and refresh.</p>
                    <a href="admin/" class="inline-flex items-center gap-2 mt-4 text-indigo-400 hover:text-indigo-300 font-semibold">Go to login &rarr;</a>
                </div>
            </div>
        <?php else: ?>

            <?php if (!empty($errors)): ?>
                <div class="bg-rose-500/10 border border-rose-500/20 text-rose-400 p-4 rounded-xl mb-8">
                    <ul class="list-disc list-inside text-sm">
                        <?php foreach($errors as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>

            <form method="POST" class="space-y-8">
                <!-- Section 1 -->
                <div class="space-y-6">
                    <h2 class="text-xl font-bold text-white flex items-center gap-3">
                        <span class="w-8 h-8 rounded-full bg-indigo-500/20 flex items-center justify-center text-sm text-indigo-400">1</span>
                        Global Config
                    </h2>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div class="md:col-span-1">
                            <label class="block text-xs font-bold uppercase tracking-wider text-gray-500 mb-2">Gallery Title</label>
                            <input type="text" name="album_title" value="Client Selection Gallery" required class="w-full px-4 py-3 rounded-xl input-dark">
                        </div>
                        <div class="md:col-span-1">
                            <label class="block text-xs font-bold uppercase tracking-wider text-gray-500 mb-2">Admin Password</label>
                            <input type="password" name="admin_password" placeholder="••••••••" required class="w-full px-4 py-3 rounded-xl input-dark">
                        </div>
                    </div>
                </div>

                <!-- Section 2 -->
                <div class="space-y-6">
                    <h2 class="text-xl font-bold text-white flex items-center gap-3">
                        <span class="w-8 h-8 rounded-full bg-indigo-500/20 flex items-center justify-center text-sm text-indigo-400">2</span>
                        Contact Links
                    </h2>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <input type="url" name="contact_telegram" placeholder="Telegram URL" class="w-full px-4 py-3 rounded-xl input-dark text-sm">
                        <input type="url" name="contact_whatsapp" placeholder="WhatsApp URL" class="w-full px-4 py-3 rounded-xl input-dark text-sm">
                        <input type="url" name="contact_facebook" placeholder="Facebook URL" class="w-full px-4 py-3 rounded-xl input-dark text-sm">
                        <input type="url" name="contact_instagram" placeholder="Instagram URL" class="w-full px-4 py-3 rounded-xl input-dark text-sm">
                        <input type="url" name="contact_signal" placeholder="Signal URL" class="w-full px-4 py-3 rounded-xl input-dark text-sm md:col-span-2">
                    </div>
                </div>

                <!-- Section 3 -->
                <div class="space-y-6">
                    <h2 class="text-xl font-bold text-white flex items-center gap-3">
                        <span class="w-8 h-8 rounded-full bg-indigo-500/20 flex items-center justify-center text-sm text-indigo-400">3</span>
                        Telegram Bot Integration
                    </h2>
                    <div class="p-6 bg-indigo-500/5 rounded-2xl border border-indigo-500/10 space-y-4">
                        <label class="flex items-center gap-3 cursor-pointer group">
                            <input type="checkbox" name="telegram_bot_enabled" class="w-5 h-5 rounded border-gray-600 bg-gray-700 text-indigo-600 focus:ring-indigo-500">
                            <span class="text-sm font-semibold text-gray-300 group-hover:text-white transition-colors">Enable instant notifications</span>
                        </label>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <input type="text" name="telegram_bot_token" placeholder="Bot Token (from @BotFather)" class="w-full px-4 py-3 rounded-xl input-dark text-sm">
                            <input type="text" name="telegram_chat_id" placeholder="Chat ID (from @userinfobot)" class="w-full px-4 py-3 rounded-xl input-dark text-sm">
                        </div>
                    </div>
                </div>

                <button type="submit" class="w-full py-4 bg-indigo-600 text-white rounded-2xl font-bold text-lg shadow-xl shadow-indigo-500/20 hover:bg-indigo-700 transition-all">
                    Finalize Setup
                </button>
            </form>

        <?php endif; ?>

        <div class="mt-12 pt-8 border-t border-white/5 flex justify-between items-center text-[10px] uppercase tracking-widest text-gray-600 font-bold">
            <p>&copy; 2024 WowkDigital Premium</p>
            <p>Built with <i data-lucide="heart" class="w-3 h-3 inline text-rose-500"></i> for photographers</p>
        </div>
    </div>

    <script>
        lucide.createIcons();
    </script>
</body>
</html>

