<?php
/**
 * Installer for photo-proofing-WD
 * Designed by WowkDigital
 */

$configFile = __DIR__ . '/api/config.php';
$configExample = __DIR__ . '/api/config.php.example';
$dbDir = __DIR__ . '/data';
$photosDir = __DIR__ . '/photos';
$logsDir = __DIR__ . '/selection_logs';

// Check if already installed
if (file_exists($configFile)) {
    $alreadyInstalled = true;
} else {
    $alreadyInstalled = false;
}

$errors = [];
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$alreadyInstalled) {
    $albumTitle = $_POST['album_title'] ?? 'My Photo Gallery';
    $password = $_POST['admin_password'] ?? '';
    $contactTelegram = $_POST['contact_telegram'] ?? '';
    $contactWhatsapp = $_POST['contact_whatsapp'] ?? '';
    $contactFacebook = $_POST['contact_facebook'] ?? '';
    $contactInstagram = $_POST['contact_instagram'] ?? '';

    if (strlen($password) < 6) {
        $errors[] = "Password must be at least 6 characters long.";
    }

    if (empty($errors)) {
        // 1. Generate config.php
        $passwordHash = password_hash($password, PASSWORD_DEFAULT);
        
        $configContent = "<?php\n";
        $configContent .= "/**\n * Configuration generated by Installer\n */\n\n";
        $configContent .= "define('ALBUM_TITLE', '" . addslashes($albumTitle) . "');\n";
        $configContent .= "define('PASSWORD_PROTECTION_ENABLED', false);\n";
        $configContent .= "define('ADMIN_PASSWORD_HASH', '" . $passwordHash . "');\n";
        $configContent .= "define('GALLERY_PASSWORD', 'change-me');\n\n";
        $configContent .= "define('CONTACT_TELEGRAM', '" . addslashes($contactTelegram) . "');\n";
        $configContent .= "define('CONTACT_FACEBOOK', '" . addslashes($contactFacebook) . "');\n";
        $configContent .= "define('CONTACT_SIGNAL', '');\n";
        $configContent .= "define('CONTACT_WHATSAPP', '" . addslashes($contactWhatsapp) . "');\n";
        $configContent .= "define('CONTACT_INSTAGRAM', '" . addslashes($contactInstagram) . "');\n";

        if (file_put_contents($configFile, $configContent)) {
            // 2. Initialize Database
            try {
                $dbPath = $dbDir . '/database.sqlite';
                $pdo = new PDO('sqlite:' . $dbPath);
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                $pdo->exec("CREATE TABLE IF NOT EXISTS albums (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    slug TEXT NOT NULL UNIQUE,
                    internal_name TEXT,
                    public_title TEXT,
                    encryption_key_hash TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
                )");

                $pdo->exec("CREATE TABLE IF NOT EXISTS photos (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    filename TEXT NOT NULL UNIQUE,
                    original_filename TEXT,
                    upload_date DATETIME DEFAULT CURRENT_TIMESTAMP,
                    album_id INTEGER REFERENCES albums(id) ON DELETE SET NULL
                )");

                $pdo->exec("CREATE TABLE IF NOT EXISTS selections (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    client_name TEXT NOT NULL,
                    client_email TEXT,
                    client_phone TEXT,
                    client_instagram TEXT,
                    client_telegram TEXT,
                    client_facebook TEXT,
                    client_notes TEXT,
                    selection_date DATETIME DEFAULT CURRENT_TIMESTAMP,
                    ip_address TEXT,
                    album_id INTEGER REFERENCES albums(id) ON DELETE SET NULL
                )");

                $pdo->exec("CREATE TABLE IF NOT EXISTS selected_photos (
                    selection_id INTEGER NOT NULL,
                    photo_filename TEXT NOT NULL,
                    FOREIGN KEY (selection_id) REFERENCES selections(id) ON DELETE CASCADE
                )");

                // Add default album
                $stmt = $pdo->query("SELECT COUNT(*) FROM albums");
                if ($stmt->fetchColumn() == 0) {
                    $pdo->exec("INSERT INTO albums (slug, internal_name, public_title) VALUES ('default', 'Main Album', '" . addslashes($albumTitle) . "')");
                }

                $success = true;
            } catch (PDOException $e) {
                $errors[] = "Database error: " . $e->getMessage();
            }
        } else {
            $errors[] = "Could not write api/config.php. Check permissions.";
        }
    }
}

// Permission Checks
$permissions = [
    'data' => is_writable($dbDir),
    'photos' => is_writable($photosDir),
    'selection_logs' => is_writable($logsDir),
    'api' => is_writable(__DIR__ . '/api')
];

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install | photo-proofing-WD</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/lucide@latest"></script>
    <style>
        body { font-family: 'Outfit', sans-serif; }
        .glass { background: rgba(255, 255, 255, 0.95); backdrop-filter: blur(10px); }
        .gradient-bg { background: linear-gradient(135deg, #6366f1 0%, #a855f7 50%, #ec4899 100%); }
    </style>
</head>
<body class="gradient-bg min-h-screen flex items-center justify-center p-4">

    <div class="glass max-w-2xl w-full rounded-3xl shadow-2xl p-8 md:p-12 transition-all duration-500 hover:shadow-indigo-500/20">
        
        <div class="flex items-center gap-4 mb-8">
            <div class="bg-indigo-600 p-3 rounded-2xl shadow-lg shadow-indigo-200">
                <i data-lucide="camera" class="text-white w-8 h-8"></i>
            </div>
            <div>
                <h1 class="text-3xl font-bold text-gray-900">Installation</h1>
                <p class="text-gray-500">photo-proofing-WD by WowkDigital</p>
            </div>
        </div>

        <?php if ($success): ?>
            <div class="bg-emerald-50 border border-emerald-200 text-emerald-700 p-6 rounded-2xl mb-8 flex items-start gap-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
                <i data-lucide="check-circle" class="w-6 h-6 shrink-0 text-emerald-500"></i>
                <div>
                    <h3 class="font-bold text-lg">Hooray! Installation Successful.</h3>
                    <p class="mt-1">Everything is set up. For security reasons, please <strong>delete install.php</strong> from your server now.</p>
                    <a href="admin/" class="inline-flex items-center gap-2 mt-4 px-6 py-2 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700 transition-all font-semibold">
                        Go to Admin Panel <i data-lucide="arrow-right" class="w-4 h-4"></i>
                    </a>
                </div>
            </div>
        <?php elseif ($alreadyInstalled): ?>
            <div class="bg-amber-50 border border-amber-200 text-amber-700 p-6 rounded-2xl mb-8 flex items-start gap-4">
                <i data-lucide="shield-alert" class="w-6 h-6 shrink-0 text-amber-500"></i>
                <div>
                    <h3 class="font-bold">Already Installed</h3>
                    <p class="mt-1">The `api/config.php` file already exists. If you want to re-run the installer, delete that file first.</p>
                </div>
            </div>
        <?php else: ?>

            <?php if (!empty($errors)): ?>
                <div class="bg-rose-50 border border-rose-200 text-rose-700 p-4 rounded-xl mb-8">
                    <ul class="list-disc list-inside">
                        <?php foreach($errors as $error): ?>
                            <li><?php echo $error; ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>

            <!-- System Check -->
            <div class="mb-10">
                <h2 class="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                    <i data-lucide="server" class="w-5 h-5 text-indigo-600"></i> System Readiness
                </h2>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
                    <?php foreach($permissions as $folder => $status): ?>
                        <div class="flex items-center justify-between p-3 rounded-xl border border-gray-100 <?php echo $status ? 'bg-white' : 'bg-rose-50 border-rose-100'; ?>">
                            <span class="text-sm font-medium text-gray-700">/<?php echo $folder; ?> writable</span>
                            <i data-lucide="<?php echo $status ? 'check-circle' : 'x-circle'; ?>" class="w-5 h-5 <?php echo $status ? 'text-emerald-500' : 'text-rose-500'; ?>"></i>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <form method="POST" class="space-y-6">
                <div class="space-y-4">
                    <h2 class="text-lg font-bold text-gray-900 flex items-center gap-2">
                        <i data-lucide="settings" class="w-5 h-5 text-indigo-600"></i> General Settings
                    </h2>
                    <div>
                        <label class="block text-sm font-semibold text-gray-700 mb-1">Gallery Title</label>
                        <input type="text" name="album_title" value="Client Photo Selection" required class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:ring-2 focus:ring-indigo-500 outline-none transition-all">
                    </div>
                </div>

                <div class="space-y-4">
                    <h2 class="text-lg font-bold text-gray-900 flex items-center gap-2">
                        <i data-lucide="lock" class="w-5 h-5 text-indigo-600"></i> Security
                    </h2>
                    <div>
                        <label class="block text-sm font-semibold text-gray-700 mb-1">Set Admin Password</label>
                        <input type="password" name="admin_password" placeholder="Min. 6 characters" required class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:ring-2 focus:ring-indigo-500 outline-none transition-all">
                        <p class="text-xs text-gray-400 mt-1">This will be used to access the /admin panel.</p>
                    </div>
                </div>

                <div class="space-y-4">
                    <h2 class="text-lg font-bold text-gray-900 flex items-center gap-2">
                        <i data-lucide="phone" class="w-5 h-5 text-indigo-600"></i> Contact Information
                    </h2>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label class="block text-sm font-semibold text-gray-700 mb-1">Telegram URL</label>
                            <input type="url" name="contact_telegram" placeholder="https://t.me/yourid" class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:ring-2 focus:ring-indigo-500 outline-none transition-all text-sm">
                        </div>
                        <div>
                            <label class="block text-sm font-semibold text-gray-700 mb-1">WhatsApp URL</label>
                            <input type="url" name="contact_whatsapp" placeholder="https://wa.me/number" class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:ring-2 focus:ring-indigo-500 outline-none transition-all text-sm">
                        </div>
                        <div>
                            <label class="block text-sm font-semibold text-gray-700 mb-1">Facebook URL</label>
                            <input type="url" name="contact_facebook" placeholder="https://fb.com/yourpage" class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:ring-2 focus:ring-indigo-500 outline-none transition-all text-sm">
                        </div>
                        <div>
                            <label class="block text-sm font-semibold text-gray-700 mb-1">Instagram URL</label>
                            <input type="url" name="contact_instagram" placeholder="https://instagr.am/user" class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:ring-2 focus:ring-indigo-500 outline-none transition-all text-sm">
                        </div>
                    </div>
                </div>

                <button type="submit" class="w-full py-4 bg-indigo-600 text-white rounded-2xl font-bold text-lg shadow-xl shadow-indigo-200 hover:bg-indigo-700 hover:-translate-y-0.5 transition-all active:scale-[0.98]">
                    Complete Installation
                </button>
            </form>

        <?php endif; ?>

        <div class="mt-8 pt-6 border-t border-gray-100 flex justify-between items-center text-xs text-gray-400">
            <p>&copy; 2024 WowkDigital</p>
            <p>Ready to go? Let's shoot! 📸</p>
        </div>
    </div>

    <script>
        lucide.createIcons();
    </script>
</body>
</html>
